Repository jenkins-x-labs/jxl, pull requests merged in 2020-03, with the labels that each got.

#22 fix: upgrade jx
  go.mod
  go.sum
Labels: size/XS

#24 fix: try use glcoud to build the image
  build.sh
  cloudbuild.yaml
  go.mod
  go.sum
  jenkins-x.yml
Labels: size/M

#28 fix: polish CLI
  cmd/root/root.go
  cmd/root/step/step.go
  go.mod
  go.sum
Labels: size/M

#33 fix: upgrade helmboot
  go.mod
  go.sum
Labels: size/XS

#34 fix: upgrade helmboot
  go.mod
  go.sum
Labels: size/XS

#37 fix: upgrade jxl-base
  Dockerfile
Labels: size/XS

#38 fix: upgrade base image
  Dockerfile
Labels: size/XS

#39 fix: upgrade base image
  Dockerfile
Labels: size/XS

#40 fix: upgrade jx
  go.mod
  go.sum
Labels: size/M

#42 fix: ugprade helmboot and base image
  Dockerfile
  go.mod
  go.sum
Labels: size/M

#43 fix: new oauth for git
  cmd/root/root.go
  go.mod
  go.sum
Labels: size/M

#47 fix: use correct image
  charts/jxl-boot/templates/install.yaml
  charts/jxl-boot/values.yaml
Labels: size/XS

#52 fix: upgrade helmboot
  go.mod
  go.sum
Labels: size/XS

#51 chore: updated jxl-boot helm3 charts
  charts/jxl-boot/.helmignore
  charts/jxl-boot/Chart.yaml
  charts/jxl-boot/Makefile
  charts/jxl-boot/templates/_helpers.tpl
  charts/jxl-boot/templates/install.yaml
  charts/jxl-boot/templates/serviceaccount.yaml
  charts/jxl-boot/values.yaml
Labels: lgtm, size/L

#58 fix: use gcr-sa instead
  jenkins-x.yml
Labels: size/XS

#59 fix: better mount
  jenkins-x.yml
Labels: size/XS

#60 fix: removed unused import
  cmd/root/get/get.go
Labels: size/XS

#61 fix: update the promote command
  promote.sh
Labels: size/XS

#62 fix: update the promote command
  go.mod
  go.sum
Labels: size/XS

#63 fix: temporary switch back to GCP SA
  charts/jxl-boot/templates/install.yaml
Labels: size/XS

#55 fix: set boot-sa serviceAccountName
  charts/jxl-boot/values.yaml
Labels: lgtm

#68 fix: use updated image
  jenkins-x.yml
Labels: size/XS

#67 chore(deps): bump https://github.com/jenkins-x-labs/step-go-releaser from v0.0.12 to 0.0.18
  dependency-matrix/matrix.md
  dependency-matrix/matrix.yaml
  go.mod
  go.sum
Labels: size/S, updatebot

#69 fix: upgrade helmboot
  cmd/root/root.go
  go.mod
  go.sum
  jenkins-x.yml
  pkg/cmd/upgrade/upgrade.go
  pkg/cmd/upgrade/upgrade_cli.go
  pkg/cmd/upgrade/upgrade_cli_test.go
  pkg/cmd/version/version.go
  pkg/cmd/version/version_test.go
  pkg/version/helpers.go
Labels: size/XL

#70 fix: upgrade helmboot
  go.mod
  go.sum
Labels: size/S

#71 fix: test cases
  pkg/cmd/upgrade/upgrade_cli_test.go
  pkg/cmd/version/test_data/common_versions/docker/gcr.io/cheese.yml
  pkg/cmd/version/test_data/common_versions/docker/maven.yml
  pkg/version/info.go
Labels: size/S

#73 fix: improve 'jxl version'
  OWNERS
  OWNERS_ALIASES
  go.mod
  go.sum
  pkg/charttest/chart_test.go
Labels: size/S

#79 fix: upgrade helmboot + jwizard
  .github/workflows/kind.yml
  Makefile
  cmd/root/get/get.go
  go.mod
  go.sum
  pkg/cmd/version/version.go
Labels: approved, size/L

#81 fix: upgrade helmboot
  .github/workflows/kind.yml
  go.mod
  go.sum
Labels: approved, size/M

#84 fix: upgrade jx and use private repos
  .github/workflows/kind.yml
  go.mod
  go.sum
Labels: size/S

#86 fix: upgrade helmboot and jx
  go.mod
  go.sum
  promote.sh
Labels: size/S

#89 fix: upgrade base image
  Dockerfile
Labels: size/XS

#91 fix: upgrade jx and jxl-base-image
  Dockerfile
  go.mod
  go.sum
Labels: size/S

#94 fix: upgrade jx
  go.mod
  go.sum
Labels: size/XS

#96 fix: upgrade helmboot and jxl-base-image
  Dockerfile
  go.mod
  go.sum
Labels: size/XS

#98 fix: latest jx
  go.mod
  go.sum
Labels: size/XS

#100 fix: upgrade jx and base image
  Dockerfile
  go.mod
  go.sum
Labels: size/S

#102 fix: upgrade jx and base image
  Dockerfile
  go.mod
  go.sum
Labels: size/S

#106 upgrade jx and base image
  Dockerfile
  go.mod
  go.sum
Labels: size/S

#109 fix: upgrade jx and helmboot
  go.mod
  go.sum
Labels: size/S

#116 fix: upgrade jx
  Dockerfile
  go.mod
  go.sum
Labels: size/S

#117 fix: upgrade jwizard
  go.mod
  go.sum
Labels: size/XS

#119 fix: add 'jxl edit deploy' command
  cmd/root/edit/edit.go
  cmd/root/root.go
  promote.sh
Labels: size/L

#118 added footer to readme
  README.md
Labels: size/XS

#124 fix: upgrade helmboot
  charts/jxl-boot/templates/install.yaml
  charts/jxl-boot/templates/serviceaccount.yaml
  charts/jxl-boot/values.yaml
  go.mod
  go.sum
Labels: size/L

#125 fix: upgrade jx
  Dockerfile
  go.mod
  go.sum
Labels: size/S

#127 fix: upgrade jx
  Dockerfile
  go.mod
  go.sum
Labels: size/S

#128 fix: upgrade jx
  Dockerfile
  go.mod
  go.sum
Labels: size/S

#130 fix: upgrade jx
  Dockerfile
  go.mod
  go.sum
Labels: size/S

#131 fix: upgrade jx
  Dockerfile
  go.mod
  go.sum
Labels: size/S

#133 fix: upgrade helmboot + jx
  Dockerfile
  go.mod
  go.sum
Labels: size/S

#137 fix: upgrade jx
  Dockerfile
  go.mod
  go.sum
Labels: size/S

#139 fix: upgrade jx
  Dockerfile
  go.mod
  go.sum
Labels: size/S

#143 fix: upgrade jx
  Dockerfile
  go.mod
  go.sum
Labels: size/S

#145 fix: upgrade helmbooot and jx
  Dockerfile
  go.mod
  go.sum
Labels: size/S

#148 fix: upgrade jx
  Dockerfile
  go.mod
  go.sum
Labels: size/S

#147 fix: create SA using helm and use SA annotation for EKS
  charts/jxl-boot/templates/serviceaccount.yaml
Labels: lgtm, size/XS
