Repository jenkins-x-labs/jxl, pull requests merged in 2020-04, with the labels that each got.

#155 fix: upgrade helmboot
  go.mod
  go.sum
Labels: size/S

#157 fix: upgrade helmboot
  go.mod
  go.sum
Labels: size/S

#158 fix: upgrade helmboot
  go.mod
  go.sum
Labels: size/XS

#159 fix: upgrade helmboot
  go.sum
Labels: size/XS

#161 fix: upgrade helmboot and jx
  Dockerfile
  go.mod
  go.sum
Labels: size/S

#163 fix: upgrade helmboot
  go.mod
  go.sum
Labels: size/XS

#165 fix: upgrade helmboot and jx
  Dockerfile
  go.mod
  go.sum
Labels: size/S

#168 fix: upgrade helmboot and jx
  go.mod
  go.sum
Labels: size/XS

#170 fix: upgrade helmboot and jx
  Dockerfile
  go.mod
  go.sum
Labels: size/S

#171 fix: upgrade helmboot
  go.mod
  go.sum
Labels: size/XS

#153 fix: use .Release.Namespace instead of from jxRequirements
  charts/jxl-boot/templates/serviceaccount.yaml
Labels: size/XS

#175 fix: upgrade helmboot and base image
  Dockerfile
  go.mod
  go.sum
Labels: size/XS

#176 chore: allow boot image tag to be overriden
  charts/jxl-boot/templates/install.yaml
  charts/jxl-boot/values.yaml
Labels: approved, size/XS

#177 fix: failing test
  cmd/root/edit/edit.go
  pkg/charttest/test_data/default/expected/batch/v1/Job/jx-boot.yaml
  pkg/charttest/test_data/eks/expected/batch/v1/Job/jx-boot.yaml
  pkg/charttest/test_data/eks/expected/v1/ServiceAccount/jxl-boot.yaml
  pkg/charttest/test_data/gke/expected/batch/v1/Job/jx-boot.yaml
Labels: approved, size/L
